"""Extraction of partial output (last non-empty text) from ExecutionTrace.responses[]."""
from typing import Dict, Any, Optional, Tuple


def extract_last_response_text(responses: list) -> Tuple[str, Optional[Dict[str, Any]]]:
    """
    Extract the last non-empty text from Responses API responses.
    
    Iterates through responses in reverse order, looking for the most recent
    non-empty output text. Compatible with extract_reasoning_and_text() logic.
    
    Criteria for matching:
    - Iterates responses in REVERSE order (most recent first)
    - Looks for output items with type "output_text" or "text" 
    - Skips "reasoning_text" as not user-facing output
    - Skips tool/function calls as not text output
    - Returns on first non-empty text found
    
    Args:
        responses: List of response dicts from ExecutionTrace.responses[]
        
    Returns:
        Tuple of (text, response_dict):
        - text: The last non-empty text found, or empty string
        - response_dict: The response entry that contained this text, or None if no text found
    """
    if not isinstance(responses, list):
        return "", None
    
    # Iterate in reverse to find the most recent response with text
    for response in reversed(responses):
        if not isinstance(response, dict):
            continue
        
        raw = response.get("raw")
        if not isinstance(raw, dict):
            continue
        
        text_parts = []
        
        # Extract from output list (same logic as extract_reasoning_and_text in yandex_client.py)
        for item in raw.get("output", []):
            if isinstance(item, dict):
                content_list = item.get("content", [])
                if isinstance(content_list, list):
                    # Iterate through content parts
                    for part in content_list:
                        if isinstance(part, dict):
                            p_type = part.get("type")
                            p_text = part.get("text", "")
                            # Only extract output_text or text, skip reasoning_text
                            if p_type in ("output_text", "text") and p_text:
                                text_parts.append(p_text)
                        elif isinstance(part, str):
                            # Raw string in content
                            text_parts.append(part)
                elif item.get("type") == "output_text" and item.get("text"):
                    # Direct output_text at item level
                    text_parts.append(str(item["text"]))
        
        # Fallback to top-level fields if nothing found in output
        if not text_parts:
            if raw.get("output_text"):
                text_parts.append(str(raw["output_text"]))
            elif raw.get("text"):
                text_parts.append(str(raw["text"]))
        
        # Clean and return if we found something
        final_text = "".join(text_parts).strip()
        if final_text:
            return final_text, response
    
    return "", None


def format_partial_output_message(partial_output: str, error: str) -> str:
    """
    Format a message combining partial output with error notice.
    
    Per spec (section 2.2):
    - If partial output exists: <output>\n\n⚠️ Ошибка: <error>
    - If no partial output: ⚠️ Ошибка: <error>
    
    Args:
        partial_output: The partial text generated by the model (may be empty)
        error: The error message
        
    Returns:
        Formatted message string
    """
    if not partial_output:
        return f"⚠️ Ошибка: {error}"
    
    return f"{partial_output}\n\n⚠️ Ошибка: {error}"
