import io
import json
import re
from datetime import UTC, datetime, timedelta
from pathlib import Path

from agent_office import observer
from agent_office.observer import (
    GitHub,
    build_thread,
    checks_state,
    classify_actor,
    detect_findings,
    render_digest,
)

ROOT = Path(__file__).resolve().parents[1]
NOW = datetime(2026, 9, 28, 18, 0, tzinfo=UTC)
CLAUDE_FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def ts(hours_ago: float) -> str:
    return (NOW - timedelta(hours=hours_ago)).strftime("%Y-%m-%dT%H:%M:%SZ")


def issue(number=1, hours_ago=10, body="", assignees=(), state="open"):
    return {
        "number": number,
        "title": f"Task {number}",
        "html_url": f"https://github.com/o/r/issues/{number}",
        "user": {"login": "maksimp6"},
        "body": body,
        "state": state,
        "created_at": ts(hours_ago),
        "assignees": [{"login": login} for login in assignees],
        "labels": [],
    }


def pr_item(number=2, hours_ago=10):
    item = issue(number, hours_ago)
    item["pull_request"] = {"url": "x"}
    item["html_url"] = f"https://github.com/o/r/pull/{number}"
    return item


def pull(ref="claude/feature", draft=False, mergeable_state="clean", merged_at=None):
    return {
        "head": {"ref": ref, "sha": "abc"},
        "base": {"ref": "master", "sha": "base"},
        "draft": draft,
        "mergeable_state": mergeable_state,
        "merged_at": merged_at,
    }


def comment(login, body, hours_ago):
    return {
        "event": "commented",
        "user": {"login": login},
        "body": body,
        "created_at": ts(hours_ago),
    }


def review(login, hours_ago, state="COMMENTED"):
    return {
        "event": "reviewed",
        "user": {"login": login},
        "state": state,
        "submitted_at": ts(hours_ago),
    }


def run(name, conclusion, status="completed", hours_ago=1):
    return {"name": name, "conclusion": conclusion, "status": status, "started_at": ts(hours_ago)}


def kinds(findings):
    return sorted(finding.kind for finding in findings)


# --- who did it -------------------------------------------------------------


def test_bots_and_signed_owner_posts_are_attributed_to_agents():
    assert classify_actor("copilot-pull-request-reviewer[bot]") == "copilot"
    assert classify_actor("Copilot") == "copilot"
    assert classify_actor("chatgpt-codex-connector[bot]") == "codex"
    assert classify_actor("claude[bot]") == "claude"
    assert classify_actor("alice-pro-maksimp6[bot]") == "alice"
    assert classify_actor("dependabot[bot]") == "ci"
    assert classify_actor("maksimp6", "plain text") == "human"
    assert classify_actor("maksimp6", "done" + CLAUDE_FOOTER) == "claude"


def test_pr_owner_comes_from_branch_prefix_then_author():
    assert build_thread(pr_item(), [], pull(ref="copilot/task-1")).owner_agent == "copilot"
    signed = pr_item()
    signed["body"] = "Change" + CLAUDE_FOOTER
    assert build_thread(signed, [], pull(ref="feat/login")).owner_agent == "claude"
    assert build_thread(pr_item(), [], pull(ref="feat/login")).owner_agent == "human"


# --- threads ----------------------------------------------------------------


def test_thread_is_chronological_and_tracks_links_and_checks():
    timeline = [
        comment("claude[bot]", "Working on it", 1),
        {
            "event": "cross-referenced",
            "actor": {"login": "maksimp6"},
            "created_at": ts(0.5),
            "source": {"issue": {"number": 9, "title": "Fix", "pull_request": {}, "html_url": "u"}},
        },
        comment("maksimp6", "@claude please take this" + CLAUDE_FOOTER, 2),
        {"event": "committed", "author": {"name": "Claude", "date": ts(1.5)}, "message": "feat: x"},
        {"event": "unknown_event", "created_at": ts(1)},
    ]
    thread = build_thread(issue(), timeline)
    assert [event.at for event in thread.events] == sorted(event.at for event in thread.events)
    assert thread.events[0].action == "открыл задачу"
    assert thread.linked_prs == [9]
    assert thread.owner_agent == "claude"
    assert thread.dispatches == [("claude", NOW - timedelta(hours=2))]

    pr = build_thread(
        pr_item(), [], pull(), [run("tests", "success"), run("lint", None, "in_progress")]
    )
    assert pr.checks == {"tests": "success", "lint": "in_progress"}
    assert checks_state(pr) == "pending"


def test_agent_bot_quoting_its_own_name_is_not_a_dispatch():
    thread = build_thread(issue(), [comment("claude[bot]", "> @claude please take this", 1)])
    assert thread.dispatches == []
    assert thread.owner_agent == "human"


def test_copilot_assignment_and_alice_label_are_dispatches():
    assigned = build_thread(issue(assignees=["Copilot"]), [])
    assert assigned.owner_agent == "copilot"
    labeled = build_thread(
        issue(),
        [
            {
                "event": "labeled",
                "actor": {"login": "maksimp6"},
                "label": {"name": "alice"},
                "created_at": ts(3),
            }
        ],
    )
    assert labeled.dispatches == [("alice", NOW - timedelta(hours=3))]


# --- findings ---------------------------------------------------------------


def test_red_ci_and_merge_conflict_are_high():
    thread = build_thread(
        pr_item(),
        [review("copilot-pull-request-reviewer[bot]", 5)],
        pull(mergeable_state="dirty"),
        [run("Application tests", "failure"), run("lint", "success")],
    )
    findings = detect_findings(thread, NOW)
    assert kinds(findings) == ["ci_failed", "merge_conflict", "no_codex_check"]
    assert {f.severity for f in findings if f.kind != "no_codex_check"} == {"high"}
    assert "Application tests" in next(f.message for f in findings if f.kind == "ci_failed")


def test_pr_maintainer_handoff_stalls_after_two_scheduled_observer_passes():
    dispatch_at = datetime(2026, 9, 28, 17, 18, tzinfo=UTC)
    base_timeline = [
        review("copilot-pull-request-reviewer[bot]", 5),
        comment("chatgpt-codex-connector[bot]", "Tests look fine", 4.5),
        {
            "event": "commented",
            "user": {"login": "maksimp6"},
            "body": "@claude-lite maintainer pass on exact head",
            "created_at": dispatch_at.isoformat(),
        },
    ]
    stalled = build_thread(pr_item(), base_timeline, pull(), [run("tests", "success")])

    first_pass = datetime(2026, 9, 28, 18, 17, tzinfo=UTC)
    second_pass = datetime(2026, 9, 28, 19, 17, tzinfo=UTC)
    assert "maintainer_stall" not in kinds(detect_findings(stalled, first_pass))
    assert "maintainer_stall" in kinds(detect_findings(stalled, second_pass))


def test_role_only_claude_mention_is_not_executable_maintainer_dispatch():
    timeline = [
        review("copilot-pull-request-reviewer[bot]", 5),
        comment("chatgpt-codex-connector[bot]", "Tests look fine", 4.5),
        comment("maksimp6", "@claude maintainer pass on exact head", 3),
    ]
    thread = build_thread(pr_item(), timeline, pull(), [run("tests", "success")])

    assert thread.dispatches == [("claude", NOW - timedelta(hours=3))]
    assert thread.executable_dispatches == []
    assert "maintainer_stall" not in kinds(detect_findings(thread, NOW))


def test_claude_lite_mention_is_executable_maintainer_dispatch():
    timeline = [
        review("copilot-pull-request-reviewer[bot]", 5),
        comment("chatgpt-codex-connector[bot]", "Tests look fine", 4.5),
        comment("maksimp6", "@claude-lite maintainer pass on exact head", 3),
    ]
    thread = build_thread(pr_item(), timeline, pull(), [run("tests", "success")])

    assert thread.dispatches == [("claude", NOW - timedelta(hours=3))]
    assert thread.executable_dispatches == [("claude", NOW - timedelta(hours=3))]
    assert "maintainer_stall" in kinds(detect_findings(thread, NOW))


def test_only_material_maintainer_status_completes_handoff():
    base = [
        review("copilot-pull-request-reviewer[bot]", 5),
        comment("chatgpt-codex-connector[bot]", "Tests look fine", 4.5),
        comment("maksimp6", "@claude-lite maintainer pass on exact head", 3),
    ]
    acknowledged = build_thread(
        pr_item(),
        [*base, comment("claude[bot]", "Looking into it", 2.5)],
        pull(),
        [run("tests", "success")],
    )
    assert "maintainer_stall" in kinds(detect_findings(acknowledged, NOW))

    blocked = build_thread(
        pr_item(),
        [*base, comment("claude[bot]", "BLOCKED: required check missing", 2.5)],
        pull(),
        [run("tests", "success")],
    )
    assert "maintainer_stall" not in kinds(detect_findings(blocked, NOW))

    deferred = build_thread(
        pr_item(),
        [*base, comment("claude[bot]", "DEFERRED: wait for master sync", 2.5)],
        pull(),
        [run("tests", "success")],
    )
    assert "maintainer_stall" not in kinds(detect_findings(deferred, NOW))

    changes = build_thread(
        pr_item(),
        [*base, review("claude[bot]", 2.5, state="CHANGES_REQUESTED")],
        pull(),
        [run("tests", "success")],
    )
    assert "maintainer_stall" not in kinds(detect_findings(changes, NOW))


def test_observer_pass_alignment_handles_dispatch_around_cron_minute():
    before = datetime(2026, 9, 28, 17, 16, tzinfo=UTC)
    after = datetime(2026, 9, 28, 17, 18, tzinfo=UTC)

    assert (
        observer._observer_passes_since(
            before,
            datetime(2026, 9, 28, 18, 17, tzinfo=UTC),
            17,
        )
        == 2
    )
    assert (
        observer._observer_passes_since(
            after,
            datetime(2026, 9, 28, 19, 17, tzinfo=UTC),
            17,
        )
        == 2
    )
    assert (
        observer._observer_passes_since(
            after,
            datetime(2026, 9, 28, 18, 16, tzinfo=UTC),
            17,
        )
        == 0
    )
    assert observer._observer_passes_since(after, after, 17) == 0
    assert (
        observer._observer_passes_since(
            after,
            datetime(2026, 9, 28, 17, 0, tzinfo=UTC),
            17,
        )
        == 0
    )


def test_green_reviewed_pr_waiting_for_merge_is_reported():
    timeline = [
        review("copilot-pull-request-reviewer[bot]", 4),
        comment("chatgpt-codex-connector[bot]", "Tests look fine", 3.5),
    ]
    thread = build_thread(pr_item(), timeline, pull(), [run("tests", "success")])
    assert kinds(detect_findings(thread, NOW)) == ["ready_to_merge"]
    assert detect_findings(thread, NOW - timedelta(hours=2)) == []


def test_ready_pr_without_reviews_and_quiet_drafts():
    fresh = build_thread(pr_item(hours_ago=0.5), [], pull(), [run("tests", "success")])
    assert detect_findings(fresh, NOW) == []
    waiting = build_thread(pr_item(hours_ago=3), [], pull(), [run("tests", "success")])
    assert kinds(detect_findings(waiting, NOW)) == ["no_codex_check", "no_copilot_review"]
    codex_asked = build_thread(
        pr_item(hours_ago=3), [comment("maksimp6", "@codex review", 2)], pull()
    )
    assert "no_codex_check" in kinds(detect_findings(codex_asked, NOW))
    codex_reviewed = build_thread(
        pr_item(hours_ago=3),
        [comment("maksimp6", "@codex review", 2), review("chatgpt-codex-connector[bot]", 1)],
        pull(),
    )
    assert "no_codex_check" not in kinds(detect_findings(codex_reviewed, NOW))
    draft = build_thread(pr_item(hours_ago=30), [], pull(draft=True))
    assert kinds(detect_findings(draft, NOW)) == ["stale"]


def test_exact_behind_by_marks_green_ci_as_stale_immediately():
    thread = build_thread(
        pr_item(),
        [
            review("copilot-pull-request-reviewer[bot]", 5),
            comment("chatgpt-codex-connector[bot]", "Tests look fine", 4.5),
        ],
        pull(),
        [run("tests", "success")],
        behind_by=3,
    )
    findings = detect_findings(thread, NOW)
    assert kinds(findings) == ["branch_stale"]
    assert "3 commit(s)" in findings[0].message
    assert "зелёный CI" in findings[0].message
    digest = render_digest([thread], findings, NOW, "o/r")
    assert "freshness: behind 3" in digest


def test_long_pending_checks_and_behind_base():
    thread = build_thread(
        pr_item(),
        [review("Copilot", 5), comment("chatgpt-codex-connector[bot]", "Looks good", 5)],
        pull(mergeable_state="behind"),
        [run("tests", None, "queued", hours_ago=3)],
    )
    assert kinds(detect_findings(thread, NOW)) == ["behind_base", "checks_stuck"]


def test_silent_agent_after_dispatch_and_answered_agent_without_pr():
    silent = build_thread(issue(), [comment("maksimp6", "@codex please add tests", 3)])
    findings = detect_findings(silent, NOW)
    assert kinds(findings) == ["agent_silent"]
    assert "Codex" in findings[0].message

    recent = build_thread(issue(), [comment("maksimp6", "@codex please add tests", 1)])
    assert detect_findings(recent, NOW) == []

    answered = build_thread(
        issue(hours_ago=60),
        [
            comment("maksimp6", "@codex go", 50),
            comment("chatgpt-codex-connector[bot]", "On it", 49),
        ],
    )
    assert kinds(detect_findings(answered, NOW)) == ["stale"]

    closed = build_thread(issue(state="closed"), [comment("maksimp6", "@codex go", 30)])
    assert detect_findings(closed, NOW) == []


# --- digest -----------------------------------------------------------------


def test_digest_groups_findings_and_neutralises_mentions():
    red = build_thread(pr_item(), [], pull(mergeable_state="dirty"), [run("tests", "failure")])
    task = build_thread(issue(3), [comment("maksimp6", "@claude <b>take</b> this", 1)])
    quiet = build_thread(issue(4, hours_ago=100), [])
    findings = [f for t in (red, task, quiet) for f in detect_findings(t, NOW)]
    digest = render_digest([red, task, quiet], findings, NOW, "o/r")

    assert digest.startswith(observer.DIGEST_MARKER)
    assert digest.count("[#2]") == 1
    assert "CI красный: tests; конфликт с master" in digest
    assert not re.search(r"@(claude|codex|alice)\b", digest)
    assert "<b>" not in digest
    assert "Задача #3" in digest
    assert "Задача #4" not in digest
    assert "Не показаны ещё 1" in digest


def test_empty_office_digest_and_size_limit(monkeypatch):
    assert "зависших задач нет" in render_digest([], [], NOW, "o/r")
    monkeypatch.setattr(observer, "ISSUE_BODY_LIMIT", 500)
    threads = [build_thread(issue(n, hours_ago=1), []) for n in range(1, 20)]
    digest = render_digest(threads, [], NOW, "o/r")
    assert len(digest) <= 500
    assert digest.endswith("сводка обрезана по размеру.\n")


# --- GitHub access ----------------------------------------------------------


class FakeResponse(io.BytesIO):
    def __init__(self, payload, headers=None):
        super().__init__(json.dumps(payload).encode())
        self.headers = headers or {}

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


class FakeGitHub:
    """Serves canned API responses and records every request."""

    def __init__(self, routes):
        self.routes = routes
        self.calls = []

    def __call__(self, request, timeout):
        path = request.full_url.replace(observer.API_ROOT, "")
        self.calls.append((request.get_method(), path, request.data))
        for prefix, response in self.routes.items():
            method, _, route = prefix.partition(" ")
            if request.get_method() == method and path.startswith(route):
                if isinstance(response, Exception):
                    raise response
                payload, headers = response if isinstance(response, tuple) else (response, {})
                return FakeResponse(payload, headers)
        raise AssertionError(f"unexpected request {request.get_method()} {path}")


def test_paginate_follows_link_headers_and_sends_token():
    next_url = "https://api.github.com/repos/o/r/issues?page=2"
    fake = FakeGitHub(
        {
            "GET /repos/o/r/issues?page=2": [{"n": 2}],
            "GET /repos/o/r/issues": ([{"n": 1}], {"Link": f'<{next_url}>; rel="next"'}),
        }
    )
    gh = GitHub("secret", "o/r", opener=fake)
    assert gh.paginate(gh.repo_path("/issues")) == [{"n": 1}, {"n": 2}]
    assert len(fake.calls) == 2


def test_run_builds_threads_and_publishes_to_tracking_issue():
    open_pr = pr_item(5, hours_ago=3)
    tracking = issue(99)
    tracking["labels"] = [{"name": observer.TRACKING_LABEL}]
    fake = FakeGitHub(
        {
            "GET /repos/o/r/issues?state=open&labels=": [tracking],
            "GET /repos/o/r/issues?state=open": [open_pr, tracking],
            "GET /repos/o/r/issues?state=closed": [],
            "GET /repos/o/r/issues/5/timeline": [review("Copilot", 2)],
            "GET /repos/o/r/pulls/5": pull(ref="codex/tests"),
            "GET /repos/o/r/commits/abc/check-runs": {"check_runs": [run("tests", "failure")]},
            "GET /repos/o/r/compare/master...abc": {"behind_by": 0},
            "PATCH /repos/o/r/issues/99": {"html_url": "https://github.com/o/r/issues/99"},
        }
    )
    result = observer.run(GitHub("t", "o/r", opener=fake), now=NOW, publish=True)

    assert [t["number"] for t in result["threads"]] == [5]
    assert result["threads"][0]["agent"] == "codex"
    assert result["threads"][0]["behind_by"] == 0
    assert result["threads"][0]["freshness"] == "current"
    assert result["threads"][0]["dispatches"] == []
    assert result["threads"][0]["executable_dispatches"] == []
    assert {f["kind"] for f in result["findings"]} == {"ci_failed", "no_codex_check"}
    assert result["tracking_issue"].endswith("/99")
    patch = next(call for call in fake.calls if call[0] == "PATCH")
    assert json.loads(patch[2])["body"] == result["digest"]


def http_error(code):
    return observer.urllib.error.HTTPError("https://api.github.com/x", code, "err", {}, None)


def test_publish_creates_label_and_tracking_issue_on_first_run():
    fake = FakeGitHub(
        {
            "GET /repos/o/r/issues?state=open&labels=": [],
            "POST /repos/o/r/labels": {"name": observer.TRACKING_LABEL},
            "POST /repos/o/r/issues": {"html_url": "https://github.com/o/r/issues/100"},
        }
    )
    url = observer.publish_digest(GitHub("t", "o/r", opener=fake), "digest")
    assert url.endswith("/100")
    assert json.loads(fake.calls[1][2])["name"] == observer.TRACKING_LABEL
    payload = json.loads(fake.calls[-1][2])
    assert payload["labels"] == [observer.TRACKING_LABEL]
    assert payload["title"] == observer.TRACKING_TITLE


def test_existing_label_is_fine_but_other_label_errors_surface():
    routes = {
        "GET /repos/o/r/issues?state=open&labels=": [],
        "POST /repos/o/r/labels": http_error(422),
        "POST /repos/o/r/issues": {"html_url": "https://github.com/o/r/issues/101"},
    }
    assert observer.publish_digest(GitHub("t", "o/r", opener=FakeGitHub(routes)), "d")
    routes["POST /repos/o/r/labels"] = http_error(403)
    try:
        observer.publish_digest(GitHub("t", "o/r", opener=FakeGitHub(routes)), "d")
    except observer.urllib.error.HTTPError as error:
        assert error.code == 403
    else:
        raise AssertionError("expected the 403 to surface")


def test_copilot_mention_is_a_dispatch_and_queued_runs_date_from_creation():
    thread = build_thread(issue(), [comment("maksimp6", "@copilot please take this", 3)])
    assert thread.owner_agent == "copilot"
    assert kinds(detect_findings(thread, NOW)) == ["agent_silent"]
    queued = {"name": "t", "conclusion": None, "status": "queued", "created_at": ts(3)}
    pr = build_thread(pr_item(), [], pull(), [queued])
    assert pr.checks_started_at == NOW - timedelta(hours=3)


def test_main_writes_summary_and_json(monkeypatch, tmp_path):
    summary = tmp_path / "summary.md"
    out = tmp_path / "out.json"
    monkeypatch.setenv("GITHUB_STEP_SUMMARY", str(summary))
    monkeypatch.setattr(
        observer,
        "run",
        lambda gh, publish: {
            "digest": "# digest\n",
            "findings": [{"severity": "high"}],
            "threads": [],
        },
    )
    assert observer.main(["--repo", "o/r", "--json-out", str(out)]) == 0
    assert observer.main(["--repo", "o/r", "--fail-on-high"]) == 1
    assert summary.read_text(encoding="utf-8").startswith("# digest")
    assert json.loads(out.read_text(encoding="utf-8"))["findings"] == [{"severity": "high"}]


# --- workflow ---------------------------------------------------------------


def test_observer_workflow_is_hourly_pinned_and_least_privilege():
    workflow = (ROOT / ".github" / "workflows" / "agent-observer.yml").read_text(encoding="utf-8")
    uses = re.findall(r"uses:\s*(\S+)", workflow)
    assert uses and all(re.fullmatch(r"[\w.-]+/[\w.-]+@[0-9a-f]{40}", ref) for ref in uses)
    assert "permissions: {}" in workflow
    assert "persist-credentials: false" in workflow
    assert 'cron: "17 * * * *"' in workflow
    assert "issues: write" in workflow
    assert "contents: write" not in workflow
    assert "pull_request_target" not in workflow
    assert "python -m agent_office.observer" in workflow
    assert "--publish" in workflow


def test_every_timeline_event_kind_is_described():
    actor = {"login": "maksimp6"}
    raw = [
        {
            "event": "assigned",
            "actor": actor,
            "assignee": {"login": "Copilot"},
            "created_at": ts(9),
        },
        {
            "event": "unassigned",
            "actor": actor,
            "assignee": {"login": "Copilot"},
            "created_at": ts(8),
        },
        {
            "event": "review_requested",
            "actor": actor,
            "requested_reviewer": {"login": "Copilot"},
            "created_at": ts(7),
        },
        {
            "event": "review_requested",
            "actor": actor,
            "requested_team": {"name": "core"},
            "created_at": ts(7),
        },
        {"event": "merged", "actor": actor, "created_at": ts(6)},
        {"event": "head_ref_force_pushed", "actor": actor, "created_at": ts(5)},
        {"event": "copilot_work_started", "created_at": ts(4)},
        {"event": "copilot_work_finished", "actor": {"login": "Copilot"}, "created_at": ts(3)},
        {"event": "committed", "author": {"name": "Claude"}, "message": "no date"},
        {"event": "commented", "user": actor, "body": "", "created_at": None},
        {"event": "commented", "user": actor, "body": "", "created_at": ts(2)},
    ]
    events = [observer.timeline_event(item) for item in raw]
    actions = [event.action if event else None for event in events]
    assert actions == [
        "назначил Copilot",
        "снял Copilot",
        "запросил ревью у Copilot",
        "запросил ревью у core",
        "смержил",
        "head ref force pushed",
        "Copilot начал работу",
        "Copilot закончил работу",
        None,
        None,
        "комментарий",
    ]
    assert events[6].actor == "Copilot" and events[6].agent == "copilot"
    assert classify_actor("") == "human"
    assert observer.parse_time(None) is None


def test_copilot_assigned_later_becomes_owner_and_long_threads_are_trimmed():
    assign = {
        "event": "assigned",
        "actor": {"login": "maksimp6"},
        "assignee": {"login": "Copilot"},
        "created_at": ts(3),
    }
    other = dict(assign, assignee={"login": "maksimp6"})
    thread = build_thread(issue(), [other, assign])
    assert thread.dispatches == [("copilot", NOW - timedelta(hours=3))]
    many = [comment("maksimp6", f"note {n}", n / 10) for n in range(1, 20)]
    digest = render_digest([build_thread(issue(), many)], [], NOW, "o/r", events_per_thread=5)
    assert "ещё 15 шагов раньше" in digest


def test_main_reports_api_errors_and_tracking_issue(monkeypatch, capsys):
    def fail(gh, publish):
        raise observer.urllib.error.HTTPError("https://api.github.com/x", 403, "no", {}, None)

    monkeypatch.setattr(observer, "run", fail)
    assert observer.main(["--repo", "o/r"]) == 2
    assert "GitHub API error 403" in capsys.readouterr().err

    monkeypatch.delenv("GITHUB_STEP_SUMMARY", raising=False)
    monkeypatch.setattr(
        observer,
        "run",
        lambda gh, publish: {
            "digest": "d",
            "findings": [],
            "threads": [],
            "tracking_issue": "https://github.com/o/r/issues/1",
        },
    )
    assert observer.main(["--repo", "o/r", "--publish"]) == 0
    assert "Tracking issue: https://github.com/o/r/issues/1" in capsys.readouterr().err


def test_codex_authored_pr_still_needs_a_codex_test_check():
    commit = {
        "event": "committed",
        "author": {"name": "chatgpt-codex-connector[bot]", "date": ts(4)},
        "message": "test: add cases",
    }
    item = pr_item(hours_ago=4)
    item["user"] = {"login": "chatgpt-codex-connector[bot]"}
    thread = build_thread(item, [commit], pull(ref="codex/tests"))
    assert thread.owner_agent == "codex"
    assert "no_codex_check" in kinds(detect_findings(thread, NOW))


def test_copilot_unassigned_before_answering_cancels_the_dispatch():
    def assignment(event, hours_ago):
        return {
            "event": event,
            "actor": {"login": "maksimp6"},
            "assignee": {"login": "Copilot"},
            "created_at": ts(hours_ago),
        }

    thread = build_thread(issue(), [assignment("assigned", 5), assignment("unassigned", 4)])
    assert thread.dispatches == []
    assert thread.owner_agent == "human"
    assert detect_findings(thread, NOW) == []


def test_digest_escapes_actor_names():
    commit = {
        "event": "committed",
        "author": {"name": "@claude <b>x</b>", "date": ts(1)},
        "message": "fix",
    }
    bot_commit = dict(commit, author={"name": "claude[bot] <i>", "date": ts(1)})
    digest = render_digest([build_thread(issue(), [commit, bot_commit])], [], NOW, "o/r")
    assert not re.search(r"@(claude|codex|alice)\b", digest)
    assert "<b>" not in digest and "<i>" not in digest


def test_cross_reference_keeps_the_referencing_actor():
    signed = {"number": 7, "title": "t", "body": "x" + CLAUDE_FOOTER, "user": {"login": "maksimp6"}}
    by_person = {
        "event": "cross-referenced",
        "actor": {"login": "someone"},
        "created_at": ts(1),
        "source": {"issue": signed},
    }
    assert observer.timeline_event(by_person).agent == "human"
    anonymous = dict(by_person, actor=None)
    event = observer.timeline_event(anonymous)
    assert (event.actor, event.agent) == ("maksimp6", "claude")


def test_only_pending_runs_date_the_checks():
    thread = build_thread(
        pr_item(),
        [review("Copilot", 5), review("chatgpt-codex-connector[bot]", 5)],
        pull(),
        [run("old", "success", hours_ago=10), run("new", None, "queued", hours_ago=0.5)],
    )
    assert thread.checks_started_at == NOW - timedelta(hours=0.5)
    assert detect_findings(thread, NOW) == []


def test_finding_messages_are_escaped_in_the_digest():
    thread = build_thread(pr_item(), [], pull(), [run("@claude <b>", "failure")])
    digest = render_digest([thread], detect_findings(thread, NOW), NOW, "o/r")
    assert not re.search(r"@claude\b", digest) and "<b>" not in digest
