"""Watch the GitHub agent office and build a readable thread for every task.

The observer reads open issues and pull requests (plus the ones closed in the
last day), turns each GitHub timeline into one chronological "thread" with the
agent behind every step, and flags work that is stuck: red CI, merge conflicts,
missing Copilot or Codex reviews, green pull requests nobody merged, and agents
that went silent after being given a task.

It only reads GitHub, except with ``--publish``: then it rewrites the body of
one tracking issue (label ``agent-observer``) with the digest. It never
comments, mentions agents, pushes, or merges; the maintainer acts on findings.

Run it locally with a token that can read the repository:

    GITHUB_TOKEN=... python -m agent_office.observer --repo maksimp6/Chat

The scheduled workflow ``.github/workflows/agent-observer.yml`` runs it hourly.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any
from collections.abc import Callable

API_ROOT = "https://api.github.com"
TRACKING_LABEL = "agent-observer"
TRACKING_TITLE = "Наблюдатель: офис агентов"
DIGEST_MARKER = "<!-- agent-office-observer -->"
ISSUE_BODY_LIMIT = 60000

AGENTS = ("claude", "codex", "copilot", "alice")
AGENT_LABELS = {
    "claude": "Claude",
    "codex": "Codex",
    "copilot": "Copilot",
    "alice": "Alice",
    "ci": "CI-бот",
    "human": "человек",
}

FAILED_CONCLUSIONS = {"failure", "timed_out", "cancelled", "action_required", "startup_failure"}
PASSED_CONCLUSIONS = {"success", "neutral", "skipped"}
SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}
SEVERITY_ICONS = {"high": "🔴", "medium": "🟡", "low": "⚪"}


@dataclass(frozen=True)
class Thresholds:
    """How long each kind of waiting is allowed before it becomes a finding."""

    agent_silent: timedelta = timedelta(hours=2)
    review_wait: timedelta = timedelta(hours=1)
    merge_wait: timedelta = timedelta(hours=2)
    maintainer_passes: int = 2
    observer_minute: int = 17
    checks_pending: timedelta = timedelta(hours=2)
    stale: timedelta = timedelta(hours=24)
    recent_window: timedelta = timedelta(hours=24)


DEFAULT_LIMITS = Thresholds()


@dataclass
class Event:
    at: datetime
    actor: str
    agent: str
    action: str
    url: str = ""
    kind: str = ""


@dataclass
class Thread:
    number: int
    title: str
    url: str
    kind: str  # "issue" or "pr"
    state: str  # "open", "closed" or "merged"
    owner_agent: str
    created_at: datetime
    events: list[Event] = field(default_factory=list)
    draft: bool = False
    mergeable_state: str = ""
    base_ref: str = ""
    head_sha: str = ""
    behind_by: int | None = None
    checks: dict[str, str] = field(default_factory=dict)
    checks_started_at: datetime | None = None
    linked_prs: list[int] = field(default_factory=list)
    dispatches: list[tuple[str, datetime]] = field(default_factory=list)
    trigger_eligible_dispatches: list[tuple[str, datetime, bool]] = field(default_factory=list)
    executable_dispatches: list[tuple[str, datetime]] = field(default_factory=list)
    maintainer_dispatches: list[tuple[str, datetime]] = field(default_factory=list)

    @property
    def last_activity(self) -> datetime:
        return max([self.created_at, *(event.at for event in self.events)])


@dataclass
class Finding:
    severity: str
    kind: str
    number: int
    title: str
    url: str
    agent: str
    message: str


# --------------------------------------------------------------------------
# Who did it


def classify_login(login: str | None) -> str:
    """Map a GitHub login or commit author name to an agent id."""
    name = (login or "").strip().lower()
    if not name:
        return "human"
    if "copilot" in name:
        return "copilot"
    if "codex" in name or name == "chatgpt-connector[bot]":
        return "codex"
    if "claude" in name or "anthropic" in name:
        return "claude"
    if "alice" in name:
        return "alice"
    if name.endswith("[bot]") or name in {"github-actions", "dependabot"}:
        return "ci"
    return "human"


_TEXT_MARKERS = (
    ("claude", re.compile(r"generated (?:with|by) \[claude code\]|claude\.ai/code", re.I)),
    ("codex", re.compile(r"chatgpt\.com/codex|generated (?:with|by) codex", re.I)),
    ("alice", re.compile(r"alice pro github agent|generated by alice", re.I)),
)


def classify_text(text: str | None) -> str | None:
    """Recognise an agent from the footer it leaves in a body, if any."""
    for agent, pattern in _TEXT_MARKERS:
        if pattern.search(text or ""):
            return agent
    return None


def classify_actor(login: str | None, text: str | None = None) -> str:
    """Bots post under their own names; agents using the owner's token sign the text."""
    agent = classify_login(login)
    if agent == "human":
        return classify_text(text) or "human"
    return agent


def classify_branch(ref: str | None) -> str | None:
    prefix = (ref or "").split("/", 1)[0].lower()
    return prefix if prefix in AGENTS else None


_MENTION = re.compile(r"(?<![\w/])@(claude|codex|copilot|alice)\b", re.I)
_EXECUTABLE_MENTION = re.compile(r"(?<![\w/])@(claude-lite|codex|copilot|alice)\b", re.I)
_EXECUTABLE_AGENT = {
    "claude-lite": "claude",
    "codex": "codex",
    "copilot": "copilot",
    "alice": "alice",
}
_MAINTAINER_INTENT = re.compile(r"\bmaintainer\b", re.I)
_EXECUTABLE_AUTHOR_ASSOCIATIONS = {"OWNER", "MEMBER", "COLLABORATOR"}
_CLAUDE_ACTION_RUN = re.compile(r"https://github\.com/[^)\s]+/actions/runs/\d+")


def mentioned_agents(text: str | None) -> list[str]:
    return sorted({match.lower() for match in _MENTION.findall(text or "")})


def executable_mentioned_agents(text: str | None) -> list[str]:
    """Return repository mention tokens that can actually start a configured backend."""
    return sorted(
        {_EXECUTABLE_AGENT[match.lower()] for match in _EXECUTABLE_MENTION.findall(text or "")}
    )


# --------------------------------------------------------------------------
# Building threads


def parse_time(value: str | None) -> datetime | None:
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _login(obj: dict[str, Any] | None) -> str:
    return (obj or {}).get("login") or ""


def _first_line(text: str | None, limit: int = 90) -> str:
    line = next((part.strip() for part in (text or "").splitlines() if part.strip()), "")
    line = re.sub(r"\s+", " ", line)
    return line if len(line) <= limit else line[: limit - 1] + "…"


def timeline_event(raw: dict[str, Any]) -> Event | None:
    """Turn one GitHub timeline entry into a thread event."""
    kind = raw.get("event") or ""
    if kind == "committed":
        author = (raw.get("author") or {}).get("name") or ""
        at = parse_time((raw.get("author") or {}).get("date"))
        message = raw.get("message") or ""
        return (
            Event(
                at,
                author,
                classify_actor(author, message),
                f"коммит «{_first_line(message)}»",
                raw.get("html_url") or "",
                kind,
            )
            if at
            else None
        )

    at = parse_time(raw.get("created_at") or raw.get("submitted_at"))
    if at is None:
        return None
    actor = _login(raw.get("user")) or _login(raw.get("actor"))
    body = raw.get("body") or ""
    url = raw.get("html_url") or ""

    if kind == "commented":
        action = f"комментарий: {_first_line(body)}" if body else "комментарий"
    elif kind == "reviewed":
        state = (raw.get("state") or "").lower()
        action = {
            "approved": "одобрил PR",
            "changes_requested": "запросил изменения",
        }.get(state, "оставил ревью")
    elif kind == "assigned":
        action = f"назначил {_login(raw.get('assignee'))}"
    elif kind == "unassigned":
        action = f"снял {_login(raw.get('assignee'))}"
    elif kind == "labeled":
        action = f"метка «{(raw.get('label') or {}).get('name', '')}»"
    elif kind == "review_requested":
        reviewer = _login(raw.get("requested_reviewer")) or (
            (raw.get("requested_team") or {}).get("name") or ""
        )
        action = f"запросил ревью у {reviewer}"
    elif kind == "cross-referenced":
        source = (raw.get("source") or {}).get("issue") or {}
        label = "PR" if "pull_request" in source else "issue"
        action = f"упомянут в {label} #{source.get('number')} «{_first_line(source.get('title'))}»"
        url = source.get("html_url") or url
        if not actor:
            # Fall back to the referencing item's author, signed footer included.
            actor = _login(source.get("user"))
            body = source.get("body") or ""
    elif kind in {"merged", "closed", "reopened", "ready_for_review", "convert_to_draft"}:
        action = {
            "merged": "смержил",
            "closed": "закрыл",
            "reopened": "переоткрыл",
            "ready_for_review": "отметил PR готовым",
            "convert_to_draft": "вернул PR в черновик",
        }[kind]
    elif kind in {"head_ref_force_pushed", "head_ref_deleted", "head_ref_restored"}:
        action = kind.replace("_", " ")
    elif kind.startswith("copilot_work"):
        action = "Copilot начал работу" if "started" in kind else "Copilot закончил работу"
        actor = actor or "Copilot"
    else:
        return None
    return Event(at, actor, classify_actor(actor, body), action, url, kind)


def build_thread(
    item: dict[str, Any],
    timeline: list[dict[str, Any]],
    pull: dict[str, Any] | None = None,
    check_runs: list[dict[str, Any]] | None = None,
    behind_by: int | None = None,
) -> Thread:
    """Assemble the thread of one issue or pull request from GitHub data."""
    is_pr = pull is not None or "pull_request" in item
    author = _login(item.get("user"))
    body = item.get("body") or ""
    created_at = parse_time(item.get("created_at")) or datetime.now(UTC)

    if is_pr:
        head = (pull or {}).get("head") or {}
        head_ref = head.get("ref")
        owner_agent = classify_branch(head_ref) or classify_actor(author, body)
        merged = bool(
            (pull or {}).get("merged_at") or (item.get("pull_request") or {}).get("merged_at")
        )
        state = "merged" if merged else item.get("state", "open")
    else:
        owner_agent = "human"
        state = item.get("state", "open")

    thread = Thread(
        number=item["number"],
        title=item.get("title") or "",
        url=item.get("html_url") or "",
        kind="pr" if is_pr else "issue",
        state=state,
        owner_agent=owner_agent,
        created_at=created_at,
        draft=bool((pull or {}).get("draft") or item.get("draft")),
        mergeable_state=(pull or {}).get("mergeable_state") or "",
        base_ref=str(((pull or {}).get("base") or {}).get("ref") or ""),
        head_sha=str(((pull or {}).get("head") or {}).get("sha") or ""),
        behind_by=behind_by,
    )
    thread.events.append(
        Event(
            created_at,
            author,
            classify_actor(author, body),
            "открыл PR" if is_pr else "открыл задачу",
            thread.url,
        )
    )
    if not is_pr:
        _record_dispatch(
            thread,
            body,
            created_at,
            author,
            author_association=item.get("author_association"),
        )
        for assignee in item.get("assignees") or []:
            if classify_login(_login(assignee)) == "copilot":
                thread.dispatches.append(("copilot", created_at))

    for raw in timeline:
        event = timeline_event(raw)
        if event is None:
            continue
        thread.events.append(event)
        kind = raw.get("event")
        if kind == "cross-referenced":
            source = (raw.get("source") or {}).get("issue") or {}
            if "pull_request" in source and source.get("number") not in thread.linked_prs:
                thread.linked_prs.append(source["number"])
        elif kind == "commented":
            if (
                event.agent in AGENTS
                and classify_login(event.actor) == event.agent
                and _is_backend_acknowledgement(event.agent, raw.get("body"), kind)
            ):
                _acknowledge_backend_dispatch(thread, event.agent, event.at)
            _record_dispatch(
                thread,
                raw.get("body"),
                event.at,
                event.actor,
                author_association=raw.get("author_association"),
            )
        elif kind == "reviewed":
            if (
                event.agent in AGENTS
                and classify_login(event.actor) == event.agent
                and _is_backend_acknowledgement(event.agent, raw.get("body"), kind)
            ):
                _acknowledge_backend_dispatch(thread, event.agent, event.at)
        elif not is_pr and kind == "assigned":
            if classify_login(_login(raw.get("assignee"))) == "copilot":
                thread.dispatches.append(("copilot", event.at))
        elif not is_pr and kind == "unassigned":
            if classify_login(_login(raw.get("assignee"))) == "copilot":
                thread.dispatches = [d for d in thread.dispatches if d[0] != "copilot"]
        elif not is_pr and kind == "labeled":
            if (raw.get("label") or {}).get("name") == "alice":
                thread.dispatches.append(("alice", event.at))

    if not is_pr:
        agents = [agent for agent, _ in thread.dispatches]
        thread.owner_agent = agents[-1] if agents else "human"

    for run in check_runs or []:
        name = run.get("name") or "check"
        thread.checks[name] = run.get("conclusion") or run.get("status") or "queued"
        started = parse_time(run.get("started_at") or run.get("created_at"))
        pending = not run.get("conclusion")
        if (
            pending
            and started
            and (thread.checks_started_at is None or started < thread.checks_started_at)
        ):
            thread.checks_started_at = started

    thread.events.sort(key=lambda event: event.at)
    return thread


def _record_dispatch(
    thread: Thread,
    text: str | None,
    at: datetime,
    actor: str,
    *,
    author_association: str | None = None,
) -> None:
    """Record mention intent separately from trigger eligibility and execution evidence."""
    poster = classify_login(actor)
    for agent in mentioned_agents(text):
        if agent != poster:
            thread.dispatches.append((agent, at))

    if (author_association or "").upper() not in _EXECUTABLE_AUTHOR_ASSOCIATIONS:
        return

    maintainer_intent = bool(thread.kind == "pr" and _MAINTAINER_INTENT.search(text or ""))
    for agent in executable_mentioned_agents(text):
        if agent != poster:
            thread.trigger_eligible_dispatches.append((agent, at, maintainer_intent))


def _is_backend_acknowledgement(agent: str, body: str | None, kind: str) -> bool:
    """Require provider-specific evidence that a trigger reached the execution backend."""
    if kind == "reviewed":
        return True
    if agent == "claude":
        return kind == "commented" and bool(_CLAUDE_ACTION_RUN.search(body or ""))
    return kind == "commented"


def _acknowledge_backend_dispatch(thread: Thread, agent: str, at: datetime) -> None:
    """Promote the latest eligible mention only after that backend visibly acknowledges it."""
    already_executed = set(thread.executable_dispatches)
    candidates = [
        candidate
        for candidate in thread.trigger_eligible_dispatches
        if candidate[0] == agent
        and candidate[1] <= at
        and (candidate[0], candidate[1]) not in already_executed
    ]
    if not candidates:
        return

    target, dispatched_at, maintainer_intent = max(candidates, key=lambda item: item[1])
    thread.executable_dispatches.append((target, dispatched_at))
    if target == "claude" and maintainer_intent:
        thread.maintainer_dispatches.append((target, dispatched_at))


# --------------------------------------------------------------------------
# Finding stuck work


def freshness_state(thread: Thread) -> str:
    """Summarise exact PR-head freshness relative to its current base ref."""
    if thread.kind != "pr" or thread.behind_by is None:
        return "unknown"
    return "current" if thread.behind_by == 0 else f"behind {thread.behind_by}"


def checks_state(thread: Thread) -> str:
    """Summarise head-commit checks as "failed", "pending", "passed" or "none"."""
    if not thread.checks:
        return "none"
    values = set(thread.checks.values())
    if values & FAILED_CONCLUSIONS:
        return "failed"
    if values <= PASSED_CONCLUSIONS:
        return "passed"
    return "pending"


def _ready_since(thread: Thread) -> datetime:
    ready = [event.at for event in thread.events if event.action == "отметил PR готовым"]
    return max(ready) if ready else thread.created_at


def _has_copilot_review(thread: Thread) -> bool:
    return any(
        event.agent == "copilot"
        and event.action in {"оставил ревью", "одобрил PR", "запросил изменения"}
        for event in thread.events
    )


def _has_codex_check(thread: Thread) -> bool:
    """Codex's own bot answered with a review or comment; a request or a Codex commit is not one."""
    return any(
        event.kind in {"reviewed", "commented"} and classify_login(event.actor) == "codex"
        for event in thread.events
    )


_MAINTAINER_STATUS = re.compile(
    r"^\s*(?:BLOCKED|DEFERRED|ЗАБЛОКИРОВАНО|ОТЛОЖЕНО)\s*:",
    re.IGNORECASE,
)


def _maintainer_outcome_after(thread: Thread, since: datetime) -> bool:
    for event in thread.events:
        if event.agent != "claude" or event.at <= since:
            continue
        if event.action == "запросил изменения":
            return True
        if event.kind == "commented":
            body = event.action.removeprefix("комментарий:").strip()
            if _MAINTAINER_STATUS.match(body):
                return True
    return False


def _observer_passes_since(since: datetime, now: datetime, minute: int) -> int:
    if now <= since:
        return 0
    boundary = since.replace(minute=minute, second=0, microsecond=0)
    if boundary <= since:
        boundary += timedelta(hours=1)
    if boundary > now:
        return 0
    return int((now - boundary).total_seconds() // 3600) + 1


def detect_findings(
    thread: Thread, now: datetime, limits: Thresholds = DEFAULT_LIMITS
) -> list[Finding]:
    """Everything about one open thread that needs the maintainer's attention."""
    if thread.state != "open":
        return []

    def finding(severity: str, kind: str, message: str) -> Finding:
        return Finding(
            severity, kind, thread.number, thread.title, thread.url, thread.owner_agent, message
        )

    found: list[Finding] = []
    idle = now - thread.last_activity

    if thread.kind == "pr":
        state = checks_state(thread)
        maintainer_since = max(
            (at for target, at in thread.maintainer_dispatches if target == "claude"),
            default=None,
        )
        if (
            maintainer_since is not None
            and _observer_passes_since(
                maintainer_since,
                now,
                limits.observer_minute,
            )
            >= limits.maintainer_passes
            and not _maintainer_outcome_after(thread, maintainer_since)
        ):
            found.append(
                finding(
                    "medium",
                    "maintainer_stall",
                    "maintainer handoff без merge, blocker/defer статуса или ответа Claude",
                )
            )
        if thread.behind_by is not None and thread.behind_by > 0:
            stale_ci = state == "passed"
            message = (
                f"ветка отстаёт от {thread.base_ref or 'base'} на {thread.behind_by} commit(s); "
                + (
                    "зелёный CI относится к устаревшей базе и не является merge-evidence"
                    if stale_ci
                    else "нужна синхронизация до финального merge preflight"
                )
            )
            found.append(finding("medium", "branch_stale", message))

        if state == "failed":
            failed = sorted(
                name for name, value in thread.checks.items() if value in FAILED_CONCLUSIONS
            )
            found.append(finding("high", "ci_failed", "CI красный: " + ", ".join(failed)))
        elif (
            state == "pending"
            and thread.checks_started_at
            and now - thread.checks_started_at > limits.checks_pending
        ):
            found.append(finding("low", "checks_stuck", "проверки идут дольше обычного"))
        if thread.mergeable_state == "dirty":
            found.append(finding("high", "merge_conflict", "конфликт с master"))

        if not thread.draft:
            waiting = now - _ready_since(thread)
            if not _has_copilot_review(thread) and waiting > limits.review_wait:
                found.append(finding("medium", "no_copilot_review", "нет ревью Copilot"))
            if not _has_codex_check(thread) and waiting > limits.review_wait:
                found.append(finding("low", "no_codex_check", "Codex ещё не проверял тесты"))
            if (
                state == "passed"
                and _has_copilot_review(thread)
                and thread.mergeable_state in {"clean", "unstable", "has_hooks", ""}
                and not (thread.behind_by is not None and thread.behind_by > 0)
                and idle > limits.merge_wait
            ):
                found.append(
                    finding("medium", "ready_to_merge", "зелёный и отревьюенный, ждёт мержа")
                )
            elif (
                thread.behind_by is None
                and thread.mergeable_state == "behind"
                and idle > limits.merge_wait
            ):
                found.append(
                    finding(
                        "low",
                        "behind_base",
                        "GitHub сообщает behind, но точный behind_by не получен",
                    )
                )

        if idle > limits.stale:
            label = "черновик" if thread.draft else "PR"
            found.append(finding("medium", "stale", f"{label} без движения {_hours(idle)}"))
        return found

    if thread.dispatches and not thread.linked_prs:
        agent, since = thread.dispatches[-1]
        answered = any(event.agent == agent and event.at >= since for event in thread.events)
        if not answered and now - since > limits.agent_silent:
            found.append(
                finding(
                    "medium",
                    "agent_silent",
                    f"{AGENT_LABELS[agent]} молчит {_hours(now - since)} после задания",
                )
            )
        elif answered and idle > limits.stale:
            found.append(
                finding("medium", "stale", f"задача у агента без PR и без движения {_hours(idle)}")
            )
    return found


def _hours(delta: timedelta) -> str:
    hours = int(delta.total_seconds() // 3600)
    return f"{hours // 24} д" if hours >= 48 else f"{hours} ч"


# --------------------------------------------------------------------------
# Digest


def render_digest(
    threads: list[Thread],
    findings: list[Finding],
    now: datetime,
    repo: str,
    limits: Thresholds = DEFAULT_LIMITS,
    events_per_thread: int = 12,
    max_threads: int = 40,
) -> str:
    """Markdown digest for the tracking issue and the workflow summary."""
    open_threads = [thread for thread in threads if thread.state == "open"]
    recent = now - limits.recent_window
    merged = [
        thread
        for thread in threads
        if thread.state == "merged"
        and any(e.action == "смержил" and e.at >= recent for e in thread.events)
    ]

    lines = [
        DIGEST_MARKER,
        "# Наблюдатель: офис агентов",
        "",
        f"Обновлено {now:%Y-%m-%d %H:%M} UTC · репозиторий `{repo}` · "
        f"открыто {sum(t.kind == 'pr' for t in open_threads)} PR и "
        f"{sum(t.kind == 'issue' for t in open_threads)} задач · "
        f"смержено за сутки {len(merged)}.",
        "",
        "| Агент | Открытые PR | Задачи в работе | Шагов за сутки |",
        "| --- | ---: | ---: | ---: |",
    ]
    steps = Counter(e.agent for t in threads for e in t.events if e.at >= recent)
    for agent in AGENTS:
        prs = sum(t.kind == "pr" and t.owner_agent == agent for t in open_threads)
        issues = sum(t.kind == "issue" and t.owner_agent == agent for t in open_threads)
        lines.append(f"| {AGENT_LABELS[agent]} | {prs} | {issues} | {steps[agent]} |")

    lines += ["", "## Требует внимания", ""]
    by_item: dict[int, list[Finding]] = {}
    for item in findings:
        by_item.setdefault(item.number, []).append(item)
    if by_item:
        worst = {n: min(SEVERITY_ORDER[f.severity] for f in group) for n, group in by_item.items()}
        for number in sorted(by_item, key=lambda n: (worst[n], -n)):
            group = sorted(by_item[number], key=lambda f: SEVERITY_ORDER[f.severity])
            head = group[0]
            lines.append(
                f"- {SEVERITY_ICONS[head.severity]} [#{number}]({head.url}) {_escape(head.title)} "
                f"({AGENT_LABELS.get(head.agent, head.agent)}): "
                + "; ".join(_escape(f.message) for f in group)
            )
    else:
        lines.append("Всё идёт по плану, зависших задач нет.")

    flagged = set(by_item)
    shown_threads = [
        t
        for t in threads
        if t.number in flagged or t.last_activity >= recent or t.owner_agent in AGENTS
    ]
    ordered = sorted(
        shown_threads,
        key=lambda t: (t.number not in flagged, t.state != "open", -t.last_activity.timestamp()),
    )[:max_threads]
    hidden = len(threads) - len(ordered)
    lines += ["", "## Треды", ""]
    if hidden:
        lines += [
            f"Не показаны ещё {hidden}: тихие задачи без агента или сверх {max_threads} тредов.",
            "",
        ]
    for thread in ordered:
        icon = {"open": "🟢", "merged": "🟣", "closed": "⚫"}.get(thread.state, "")
        kind = "PR" if thread.kind == "pr" else "Задача"
        draft = " · черновик" if thread.draft else ""
        ci = "" if thread.kind == "issue" else f" · CI: {checks_state(thread)}"
        freshness = "" if thread.kind == "issue" else f" · freshness: {freshness_state(thread)}"
        links = (
            f" · PR {', '.join(f'#{n}' for n in thread.linked_prs)}" if thread.linked_prs else ""
        )
        owner = AGENT_LABELS.get(thread.owner_agent, thread.owner_agent)
        lines.append(
            f"<details><summary>{icon} {kind} #{thread.number} {_escape(thread.title)} · "
            f"{owner}{draft}{ci}{freshness}{links}</summary>"
        )
        lines.append("")
        lines.append(f"[Открыть на GitHub]({thread.url})")
        lines.append("")
        shown = thread.events[-events_per_thread:]
        if len(thread.events) > len(shown):
            lines.append(f"- … ещё {len(thread.events) - len(shown)} шагов раньше")
        for event in shown:
            who = AGENT_LABELS.get(event.agent, event.agent)
            actor = f" ({_escape(event.actor)})" if event.actor and event.agent != "human" else ""
            if event.agent == "human":
                who = _escape(event.actor) or who
            lines.append(f"- {event.at:%m-%d %H:%M} **{who}**{actor}: {_escape(event.action)}")
        lines += ["", "</details>"]

    text = "\n".join(lines) + "\n"
    if len(text) > ISSUE_BODY_LIMIT:
        text = (
            text[: ISSUE_BODY_LIMIT - 60].rsplit("\n", 1)[0] + "\n\n… сводка обрезана по размеру.\n"
        )
    return text


def _escape(text: str) -> str:
    """Keep quoted text inert: no HTML, and no @mentions that would ping or wake agents."""
    return text.replace("<", "&lt;").replace(">", "&gt;").replace("@", "@\u200b")


# --------------------------------------------------------------------------
# GitHub access


class GitHub:
    """Minimal GitHub REST client on the standard library."""

    def __init__(self, token: str, repo: str, opener: Callable[..., Any] | None = None):
        self.token = token
        self.repo = repo
        self._open = opener or urllib.request.urlopen

    def request(self, method: str, path: str, payload: Any = None) -> tuple[Any, dict[str, str]]:
        url = path if path.startswith("https://") else f"{API_ROOT}{path}"
        data = json.dumps(payload).encode() if payload is not None else None
        req = urllib.request.Request(url, data=data, method=method)
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        req.add_header("User-Agent", "alice-agent-office-observer")
        if self.token:
            req.add_header("Authorization", f"Bearer {self.token}")
        if data is not None:
            req.add_header("Content-Type", "application/json")
        with self._open(req, timeout=30) as response:
            body = response.read()
            headers = {key.lower(): value for key, value in response.headers.items()}
        return (json.loads(body) if body else None), headers

    def get(self, path: str) -> Any:
        return self.request("GET", path)[0]

    def paginate(self, path: str, key: str | None = None, limit: int = 1000) -> list[Any]:
        items: list[Any] = []
        url: str | None = path
        while url and len(items) < limit:
            page, headers = self.request("GET", url)
            items.extend(page[key] if key else page)
            url = _next_link(headers.get("link", ""))
        return items[:limit]

    def repo_path(self, suffix: str) -> str:
        return f"/repos/{self.repo}{suffix}"


def _next_link(header: str) -> str | None:
    for part in header.split(","):
        section = part.split(";")
        if len(section) > 1 and 'rel="next"' in section[1]:
            return section[0].strip()[1:-1]
    return None


def collect_threads(
    gh: GitHub, now: datetime, limits: Thresholds = DEFAULT_LIMITS, workers: int = 8
) -> list[Thread]:
    """Read open items and those closed recently, then build their threads in parallel."""
    since = (now - limits.recent_window).strftime("%Y-%m-%dT%H:%M:%SZ")
    open_items = gh.paginate(gh.repo_path("/issues?state=open&per_page=100"), limit=300)
    closed_items = gh.paginate(
        gh.repo_path(f"/issues?state=closed&per_page=100&since={urllib.parse.quote(since)}"),
        limit=200,
    )
    items = [
        item
        for item in open_items + closed_items
        if not any(label.get("name") == TRACKING_LABEL for label in item.get("labels") or [])
        and (
            item.get("state") == "open"
            or (parse_time(item.get("closed_at")) or now) >= now - limits.recent_window
        )
    ]

    def load(item: dict[str, Any]) -> Thread:
        number = item["number"]
        timeline = gh.paginate(gh.repo_path(f"/issues/{number}/timeline?per_page=100"), limit=500)
        pull = None
        runs: list[dict[str, Any]] = []
        behind_by: int | None = None
        if "pull_request" in item:
            pull = gh.get(gh.repo_path(f"/pulls/{number}"))
            if item.get("state") == "open":
                sha = pull["head"]["sha"]
                base_ref = pull["base"]["ref"]
                runs = gh.paginate(
                    gh.repo_path(f"/commits/{sha}/check-runs?per_page=100"),
                    key="check_runs",
                    limit=300,
                )
                compare = gh.get(
                    gh.repo_path(
                        f"/compare/{urllib.parse.quote(base_ref, safe='')}...{urllib.parse.quote(sha, safe='')}"
                    )
                )
                behind_by = int(compare["behind_by"])
        return build_thread(item, timeline, pull, runs, behind_by=behind_by)

    with ThreadPoolExecutor(max_workers=workers, thread_name_prefix="observer") as pool:
        return list(pool.map(load, items))


def ensure_tracking_label(gh: GitHub) -> None:
    """Create the tracking label so the next run can find the issue by it."""
    try:
        gh.request(
            "POST",
            gh.repo_path("/labels"),
            {
                "name": TRACKING_LABEL,
                "color": "5319e7",
                "description": "Digest of the agent observer",
            },
        )
    except urllib.error.HTTPError as error:
        if error.code != 422:  # 422: the label already exists
            raise


def publish_digest(gh: GitHub, digest: str) -> str:
    """Rewrite the tracking issue with the digest, creating it on first run."""
    existing = gh.get(gh.repo_path(f"/issues?state=open&labels={TRACKING_LABEL}&per_page=10")) or []
    existing = [issue for issue in existing if "pull_request" not in issue]
    if existing:
        number = existing[0]["number"]
        issue = gh.request("PATCH", gh.repo_path(f"/issues/{number}"), {"body": digest})[0]
    else:
        ensure_tracking_label(gh)
        issue = gh.request(
            "POST",
            gh.repo_path("/issues"),
            {"title": TRACKING_TITLE, "body": digest, "labels": [TRACKING_LABEL]},
        )[0]
    return issue["html_url"]


# --------------------------------------------------------------------------
# Entry point


def run(
    gh: GitHub,
    now: datetime | None = None,
    publish: bool = False,
    limits: Thresholds = DEFAULT_LIMITS,
) -> dict[str, Any]:
    now = now or datetime.now(UTC)
    threads = collect_threads(gh, now, limits)
    findings = [finding for thread in threads for finding in detect_findings(thread, now, limits)]
    digest = render_digest(threads, findings, now, gh.repo, limits)
    result: dict[str, Any] = {
        "generated_at": now.isoformat(),
        "repo": gh.repo,
        "findings": [asdict(finding) for finding in findings],
        "threads": [
            {
                "number": t.number,
                "kind": t.kind,
                "state": t.state,
                "agent": t.owner_agent,
                "title": t.title,
                "base_ref": t.base_ref or None,
                "head_sha": t.head_sha or None,
                "behind_by": t.behind_by,
                "freshness": freshness_state(t) if t.kind == "pr" else None,
                "dispatches": [
                    {"agent": agent, "at": at.isoformat()} for agent, at in t.dispatches
                ],
                "trigger_eligible_dispatches": [
                    {
                        "agent": agent,
                        "at": at.isoformat(),
                        "maintainer_intent": maintainer_intent,
                    }
                    for agent, at, maintainer_intent in t.trigger_eligible_dispatches
                ],
                "executable_dispatches": [
                    {"agent": agent, "at": at.isoformat()} for agent, at in t.executable_dispatches
                ],
                "maintainer_dispatches": [
                    {"agent": agent, "at": at.isoformat()} for agent, at in t.maintainer_dispatches
                ],
                "events": [{**asdict(event), "at": event.at.isoformat()} for event in t.events],
            }
            for t in threads
        ],
        "digest": digest,
    }
    if publish:
        result["tracking_issue"] = publish_digest(gh, digest)
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "maksimp6/Chat"))
    parser.add_argument("--publish", action="store_true", help="update the tracking issue")
    parser.add_argument("--json-out", help="write threads and findings as JSON to this file")
    parser.add_argument(
        "--fail-on-high",
        action="store_true",
        help="exit 1 when a high-severity finding exists",
    )
    args = parser.parse_args(argv)

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN") or ""
    gh = GitHub(token, args.repo)
    try:
        result = run(gh, publish=args.publish)
    except urllib.error.HTTPError as error:
        print(f"GitHub API error {error.code} for {error.url}", file=sys.stderr)
        return 2

    digest = result["digest"]
    print(digest)
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as handle:
            handle.write(digest)
    if args.json_out:
        with open(args.json_out, "w", encoding="utf-8") as handle:
            json.dump(
                {k: v for k, v in result.items() if k != "digest"},
                handle,
                ensure_ascii=False,
                indent=2,
            )
    if result.get("tracking_issue"):
        print(f"Tracking issue: {result['tracking_issue']}", file=sys.stderr)
    high = [f for f in result["findings"] if f["severity"] == "high"]
    return 1 if args.fail_on_high and high else 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
